# Generated by Django 6.1.1 on 2026-09-12 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('history', 'history'), ('art', 'art'), ('culture', 'culture'), ('romance', 'romance'), ('sci-fi', 'sci-fi'), ('fantasy', 'fantasy'), ('mystery', 'mystery'), ('thriller', 'thriller'), ('horror', 'horror'), ('thriller', 'thriller'), ('thriller', 'thriller'), ('thriller', 'thriller')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('photo_author', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('rental_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rental_period', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'available'), ('rented', 'rented'), ('sold', 'sold')], max_length=50, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lms_app.category')),
            ],
        ),
    ]
